file=coling2012
all:
		pdflatex $(file).tex
		bibtex $(file)
		pdflatex $(file).tex
		pdflatex $(file).tex
#  latex $(file).tex
#	latex $(file).tex
#	dvips $(file).dvi
#	ps2pdf $(file).ps
#	xdg-open $(file).pdf
